type TrigramDefinition = {
  id: string;
  name: string;
  bits: string;
  element: "金" | "木" | "水" | "火" | "土";
  lowerBranches: [string, string, string];
  upperBranches: [string, string, string];
};

type HexagramDefinition = {
  code: string;
  name: string;
};

export const trigramDefinitions: TrigramDefinition[] = [
  { id: "qian", name: "乾", bits: "111", element: "金", lowerBranches: ["子", "寅", "辰"], upperBranches: ["午", "申", "戌"] },
  { id: "dui", name: "兑", bits: "110", element: "金", lowerBranches: ["巳", "卯", "丑"], upperBranches: ["亥", "酉", "未"] },
  { id: "li", name: "离", bits: "101", element: "火", lowerBranches: ["卯", "丑", "亥"], upperBranches: ["酉", "未", "巳"] },
  { id: "zhen", name: "震", bits: "100", element: "木", lowerBranches: ["子", "寅", "辰"], upperBranches: ["午", "申", "戌"] },
  { id: "xun", name: "巽", bits: "011", element: "木", lowerBranches: ["丑", "亥", "酉"], upperBranches: ["未", "巳", "卯"] },
  { id: "kan", name: "坎", bits: "010", element: "水", lowerBranches: ["寅", "辰", "午"], upperBranches: ["申", "戌", "子"] },
  { id: "gen", name: "艮", bits: "001", element: "土", lowerBranches: ["辰", "午", "申"], upperBranches: ["戌", "子", "寅"] },
  { id: "kun", name: "坤", bits: "000", element: "土", lowerBranches: ["未", "巳", "卯"], upperBranches: ["丑", "亥", "酉"] },
];

export const hexagramLookup: Record<string, HexagramDefinition> = {
  "乾-乾": { code: "1", name: "乾为天" },
  "乾-兑": { code: "10", name: "天泽履" },
  "乾-离": { code: "13", name: "天火同人" },
  "乾-震": { code: "25", name: "天雷无妄" },
  "乾-巽": { code: "44", name: "天风姤" },
  "乾-坎": { code: "6", name: "天水讼" },
  "乾-艮": { code: "33", name: "天山遁" },
  "乾-坤": { code: "12", name: "天地否" },
  "兑-乾": { code: "43", name: "泽天夬" },
  "兑-兑": { code: "58", name: "兑为泽" },
  "兑-离": { code: "49", name: "泽火革" },
  "兑-震": { code: "17", name: "泽雷随" },
  "兑-巽": { code: "28", name: "泽风大过" },
  "兑-坎": { code: "47", name: "泽水困" },
  "兑-艮": { code: "31", name: "泽山咸" },
  "兑-坤": { code: "45", name: "泽地萃" },
  "离-乾": { code: "14", name: "火天大有" },
  "离-兑": { code: "38", name: "火泽睽" },
  "离-离": { code: "30", name: "离为火" },
  "离-震": { code: "21", name: "火雷噬嗑" },
  "离-巽": { code: "50", name: "火风鼎" },
  "离-坎": { code: "64", name: "火水未济" },
  "离-艮": { code: "56", name: "火山旅" },
  "离-坤": { code: "35", name: "火地晋" },
  "震-乾": { code: "34", name: "雷天大壮" },
  "震-兑": { code: "54", name: "雷泽归妹" },
  "震-离": { code: "55", name: "雷火丰" },
  "震-震": { code: "51", name: "震为雷" },
  "震-巽": { code: "32", name: "雷风恒" },
  "震-坎": { code: "40", name: "雷水解" },
  "震-艮": { code: "62", name: "雷山小过" },
  "震-坤": { code: "16", name: "雷地豫" },
  "巽-乾": { code: "9", name: "风天小畜" },
  "巽-兑": { code: "61", name: "风泽中孚" },
  "巽-离": { code: "37", name: "风火家人" },
  "巽-震": { code: "42", name: "风雷益" },
  "巽-巽": { code: "57", name: "巽为风" },
  "巽-坎": { code: "59", name: "风水涣" },
  "巽-艮": { code: "53", name: "风山渐" },
  "巽-坤": { code: "20", name: "风地观" },
  "坎-乾": { code: "5", name: "水天需" },
  "坎-兑": { code: "60", name: "水泽节" },
  "坎-离": { code: "63", name: "水火既济" },
  "坎-震": { code: "3", name: "水雷屯" },
  "坎-巽": { code: "48", name: "水风井" },
  "坎-坎": { code: "29", name: "坎为水" },
  "坎-艮": { code: "39", name: "水山蹇" },
  "坎-坤": { code: "7", name: "地水师" },
  "艮-乾": { code: "26", name: "山天大畜" },
  "艮-兑": { code: "41", name: "山泽损" },
  "艮-离": { code: "22", name: "山火贲" },
  "艮-震": { code: "27", name: "山雷颐" },
  "艮-巽": { code: "18", name: "山风蛊" },
  "艮-坎": { code: "4", name: "山水蒙" },
  "艮-艮": { code: "52", name: "艮为山" },
  "艮-坤": { code: "15", name: "地山谦" },
  "坤-乾": { code: "11", name: "地天泰" },
  "坤-兑": { code: "19", name: "地泽临" },
  "坤-离": { code: "36", name: "地火明夷" },
  "坤-震": { code: "24", name: "地雷复" },
  "坤-巽": { code: "46", name: "地风升" },
  "坤-坎": { code: "8", name: "水地比" },
  "坤-艮": { code: "23", name: "山地剥" },
  "坤-坤": { code: "2", name: "坤为地" },
};

export const palaceByHexagramCode: Record<string, { palace: string; selfLine: 1 | 2 | 3 | 4 | 5 | 6; responseLine: 1 | 2 | 3 | 4 | 5 | 6 }> = {
  "1": { palace: "乾宫", selfLine: 6, responseLine: 3 },
  "44": { palace: "乾宫", selfLine: 1, responseLine: 4 },
  "33": { palace: "乾宫", selfLine: 2, responseLine: 5 },
  "12": { palace: "乾宫", selfLine: 3, responseLine: 6 },
  "20": { palace: "乾宫", selfLine: 4, responseLine: 1 },
  "23": { palace: "乾宫", selfLine: 5, responseLine: 2 },
  "35": { palace: "乾宫", selfLine: 4, responseLine: 1 },
  "14": { palace: "乾宫", selfLine: 3, responseLine: 6 },
  "58": { palace: "兑宫", selfLine: 6, responseLine: 3 },
  "47": { palace: "兑宫", selfLine: 1, responseLine: 4 },
  "45": { palace: "兑宫", selfLine: 2, responseLine: 5 },
  "31": { palace: "兑宫", selfLine: 3, responseLine: 6 },
  "39": { palace: "兑宫", selfLine: 4, responseLine: 1 },
  "15": { palace: "兑宫", selfLine: 5, responseLine: 2 },
  "62": { palace: "兑宫", selfLine: 4, responseLine: 1 },
  "54": { palace: "兑宫", selfLine: 3, responseLine: 6 },
  "30": { palace: "离宫", selfLine: 6, responseLine: 3 },
  "56": { palace: "离宫", selfLine: 1, responseLine: 4 },
  "50": { palace: "离宫", selfLine: 2, responseLine: 5 },
  "64": { palace: "离宫", selfLine: 3, responseLine: 6 },
  "4": { palace: "离宫", selfLine: 4, responseLine: 1 },
  "59": { palace: "离宫", selfLine: 5, responseLine: 2 },
  "6": { palace: "离宫", selfLine: 4, responseLine: 1 },
  "13": { palace: "离宫", selfLine: 3, responseLine: 6 },
  "51": { palace: "震宫", selfLine: 6, responseLine: 3 },
  "16": { palace: "震宫", selfLine: 1, responseLine: 4 },
  "40": { palace: "震宫", selfLine: 2, responseLine: 5 },
  "32": { palace: "震宫", selfLine: 3, responseLine: 6 },
  "46": { palace: "震宫", selfLine: 4, responseLine: 1 },
  "48": { palace: "震宫", selfLine: 5, responseLine: 2 },
  "28": { palace: "震宫", selfLine: 4, responseLine: 1 },
  "17": { palace: "震宫", selfLine: 3, responseLine: 6 },
  "57": { palace: "巽宫", selfLine: 6, responseLine: 3 },
  "9": { palace: "巽宫", selfLine: 1, responseLine: 4 },
  "37": { palace: "巽宫", selfLine: 2, responseLine: 5 },
  "42": { palace: "巽宫", selfLine: 3, responseLine: 6 },
  "25": { palace: "巽宫", selfLine: 4, responseLine: 1 },
  "21": { palace: "巽宫", selfLine: 5, responseLine: 2 },
  "27": { palace: "巽宫", selfLine: 4, responseLine: 1 },
  "18": { palace: "巽宫", selfLine: 3, responseLine: 6 },
  "29": { palace: "坎宫", selfLine: 6, responseLine: 3 },
  "60": { palace: "坎宫", selfLine: 1, responseLine: 4 },
  "3": { palace: "坎宫", selfLine: 2, responseLine: 5 },
  "63": { palace: "坎宫", selfLine: 3, responseLine: 6 },
  "49": { palace: "坎宫", selfLine: 4, responseLine: 1 },
  "55": { palace: "坎宫", selfLine: 5, responseLine: 2 },
  "36": { palace: "坎宫", selfLine: 4, responseLine: 1 },
  "7": { palace: "坎宫", selfLine: 3, responseLine: 6 },
  "52": { palace: "艮宫", selfLine: 6, responseLine: 3 },
  "22": { palace: "艮宫", selfLine: 1, responseLine: 4 },
  "26": { palace: "艮宫", selfLine: 2, responseLine: 5 },
  "41": { palace: "艮宫", selfLine: 3, responseLine: 6 },
  "38": { palace: "艮宫", selfLine: 4, responseLine: 1 },
  "10": { palace: "艮宫", selfLine: 5, responseLine: 2 },
  "61": { palace: "艮宫", selfLine: 4, responseLine: 1 },
  "53": { palace: "艮宫", selfLine: 3, responseLine: 6 },
  "2": { palace: "坤宫", selfLine: 6, responseLine: 3 },
  "24": { palace: "坤宫", selfLine: 1, responseLine: 4 },
  "19": { palace: "坤宫", selfLine: 2, responseLine: 5 },
  "11": { palace: "坤宫", selfLine: 3, responseLine: 6 },
  "34": { palace: "坤宫", selfLine: 4, responseLine: 1 },
  "43": { palace: "坤宫", selfLine: 5, responseLine: 2 },
  "5": { palace: "坤宫", selfLine: 4, responseLine: 1 },
  "8": { palace: "坤宫", selfLine: 3, responseLine: 6 },
};

export const branchElementMap: Record<string, "金" | "木" | "水" | "火" | "土"> = {
  子: "水",
  丑: "土",
  寅: "木",
  卯: "木",
  辰: "土",
  巳: "火",
  午: "火",
  未: "土",
  申: "金",
  酉: "金",
  戌: "土",
  亥: "水",
};
